In [2]:
import numpy as np
a = np.array([0,1,2,3])
b = np.array([[0,1,2],[3,4,5]])
c = np.array([[[1], [2]], [[3],[4]]])

In [3]:
a.ndim

1

In [4]:
b.ndim

2

In [5]:
c.ndim

3

In [6]:
a.shape

(4,)

In [7]:
b.shape

(2, 3)

In [8]:
c.shape

(2, 2, 1)

In [10]:
len(a)

4

In [17]:
len(b)

2

In [18]:
len(c)

2

In [20]:
a.size

4

In [21]:
b.size

6

In [22]:
c.size

4

In [23]:
b.dtype.name

'int32'

In [26]:
A = np.zeros((3,4), dtype=np.float)

In [27]:
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
B = np.ones((2,3,4), dtype=np.int16)

In [29]:
B

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [32]:
D = np.arange(10,25,5)

In [33]:
D

array([10, 15, 20])

In [5]:
E = np.linspace(0, 2, 11)

In [6]:
E

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [37]:
F = np.full((2,2),7)

In [38]:
F

array([[7, 7],
       [7, 7]])

In [42]:
G = np.eye(3)

In [43]:
G

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
H = np.random.random((3,3))

In [8]:
H

array([[0.87681503, 0.56149898, 0.5063766 ],
       [0.80951595, 0.45232129, 0.07706529],
       [0.17135643, 0.41465883, 0.11222881]])

In [51]:
I = np.empty((2,3))

In [52]:
I

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[1.5,2,3], [4,5,6]])

In [11]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [55]:
a+b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [56]:
b-a

array([[0.5, 0. , 0. ],
       [3. , 3. , 3. ]])

In [57]:
a/b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [58]:
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [59]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [60]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [61]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [62]:
np.sin(a)

array([[0.84147098, 0.90929743, 0.14112001],
       [0.84147098, 0.90929743, 0.14112001]])

In [63]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [64]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [0.        , 0.69314718, 1.09861229]])

In [15]:
b.T

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [14]:
a.dot(b.T)

array([[14.5, 32. ],
       [14.5, 32. ]])

In [66]:
a.dot(np.transpose(b))

array([[14.5, 32. ],
       [14.5, 32. ]])

In [67]:
a.sum()

12

In [16]:
a.min(), a.max()

(1, 3)

In [17]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [69]:
b.max(axis=0)

array([4., 5., 6.])

In [70]:
b.max(axis=1)

array([3., 6.])

In [71]:
a.mean()

2.0

In [80]:
np.median(b)

3.5

In [21]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
np.median(b, axis=0)

array([2.75, 3.5 , 4.5 ])

In [23]:
np.median(b, axis=1)

array([2., 5.])

In [83]:
np.median(b, axis=0)

array([2.75, 3.5 , 4.5 ])

In [29]:
b = np.array([[1.5,2,2.7], [4,5,6]])

In [27]:
b

array([[1.5, 2. , 2.5],
       [4. , 5. , 6. ]])

In [79]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [30]:
np.corrcoef(b)

array([[1.        , 0.99540227],
       [0.99540227, 1.        ]])

In [85]:
np.std(a)

0.816496580927726

In [86]:
np.std(b)

1.5920810978785667

In [31]:
a = np.array([3,2,1])
b = np.array([[1.5,3,2],[4,-6,5]], dtype = float)
c = np.array([[[2,1.5,6],[7,5,3]], [[3,2,4],[6,5,1]]])

In [32]:
from pprint import pprint
pprint(np.sort(a))

array([1, 2, 3])


In [35]:
pprint(b)

array([[ 1.5,  3. ,  2. ],
       [ 4. , -6. ,  5. ]])


In [133]:
pprint(np.sort(b))
pprint(np.sort(b, axis=0))

array([[ 1.5,  2. ,  3. ],
       [-6. ,  4. ,  5. ]])
array([[ 1.5, -6. ,  2. ],
       [ 4. ,  3. ,  5. ]])


In [39]:
pprint(np.sort(b, axis=1))

array([[ 1.5,  2. ,  3. ],
       [-6. ,  4. ,  5. ]])


In [40]:
c

array([[[2. , 1.5, 6. ],
        [7. , 5. , 3. ]],

       [[3. , 2. , 4. ],
        [6. , 5. , 1. ]]])

In [41]:
c.shape

(2, 2, 3)

In [128]:
pprint(np.sort(c, axis=2))

array([[[1.5, 2. , 6. ],
        [3. , 5. , 7. ]],

       [[2. , 3. , 4. ],
        [1. , 5. , 6. ]]])


In [127]:
pprint(np.sort(c, axis=1))

array([[[2. , 1.5, 3. ],
        [7. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [6. , 5. , 4. ]]])


In [135]:
pprint(np.sort(c, axis=0))

array([[[2. , 1.5, 4. ],
        [6. , 5. , 1. ]],

       [[3. , 2. , 6. ],
        [7. , 5. , 3. ]]])


In [130]:
pprint(np.sort(c))

array([[[1.5, 2. , 6. ],
        [3. , 5. , 7. ]],

       [[2. , 3. , 4. ],
        [1. , 5. , 6. ]]])


In [42]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
pprint(np.arange(1, 10).reshape(3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [43]:
np.arange(9, 0, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [6]:
pprint(np.arange(9, 0, -1).reshape(3, 3))

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])


In [44]:
a = np.arange(1, 10).reshape(3, 3)

In [46]:
pprint(a.sum())

45


In [47]:
pprint(np.sum(a))

45


In [49]:
a.shape

(3, 3)

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
pprint(a.sum(axis=0))

array([12, 15, 18])


In [13]:
pprint(np.sum(a, axis=0))

array([12, 15, 18])


In [14]:
pprint(a.sum(axis=1))

array([ 6, 15, 24])


In [15]:
pprint(a.max(axis=0))

array([7, 8, 9])


In [16]:
pprint(a.max(axis=1))

array([3, 6, 9])


In [18]:
pprint(a.cumsum())

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)


In [19]:
pprint(a.cumsum(axis=0))

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)


In [20]:
pprint(a.cumsum(axis=1))

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)


In [21]:
pprint(a.T)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])


In [22]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[1.5,2,3], [4,5,6]])

In [24]:
pprint(np.corrcoef(b))

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])


In [25]:
pprint(np.std(b, axis=1))

array([0.62360956, 0.81649658])


In [54]:
a = np.arange(1, 25).reshape(4, 6)
b = np.arange(25, 49).reshape(4, 6)
pprint(a)
pprint(b)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])
array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])


In [27]:
pprint(a+b)

array([[26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70, 72]])


In [55]:
pprint(a+100)

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])


In [56]:
new_arr = np.full_like(a, 100)
pprint(new_arr)

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])


In [57]:
pprint(a+new_arr)

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])


In [31]:
a = np.arange(5).reshape((1, 5))
b = a.T
pprint(a)
pprint(b)

array([[0, 1, 2, 3, 4]])
array([[0],
       [1],
       [2],
       [3],
       [4]])


In [32]:
pprint(a+b)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])


In [59]:
# 데모 배열 생성
a1 = np.arange(1, 25).reshape((4, 6)) #2차원 배열
pprint(a1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])


In [60]:
b = a1[1:3, 1:5]
pprint(b)

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])


In [62]:
c = a1[1:-1, 1:-1]
pprint(c)

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])


In [38]:
# 슬라이싱을 적용하여 참조한 4개 요소 업데이트 및 슬라이싱 배열 조회
c[:, 1:3]=99999
pprint(c)
# 원본 배열에 반영된 결과 확인
pprint(a1)

array([[    8, 99999, 99999,    11],
       [   14, 99999, 99999,    17]])
array([[    1,     2,     3,     4,     5,     6],
       [    7,     8, 99999, 99999,    11,    12],
       [   13,    14, 99999, 99999,    17,    18],
       [   19,    20,    21,    22,    23,    24]])


In [63]:
a = np.random.randint(1, 10, (2, 3))
pprint(a)
b = a.ravel()
pprint(b)

array([[5, 9, 5],
       [8, 5, 1]])
array([5, 9, 5, 8, 5, 1])


In [40]:
b[0] = 99
pprint(b)
pprint(a)

array([99,  1,  9,  2,  5,  3])
array([[99,  1,  9],
       [ 2,  5,  3]])


In [48]:
# 분할 대상 배열 생성
A = np.arange(1, 25)
a = A.reshape((4, 6))
pprint(a)
b = np.hsplit(a, 2)
pprint(b)
c = np.hsplit(a, 3)
pprint(c)
c = np.hsplit(a, [1,3,5])
pprint(c)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]),
 array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]),
 array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]),
 array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
[array([[ 1],
       [ 7],
       [13],
       [19]]),
 array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]),
 array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]]),
 array([[ 6],
       [12],
       [18],
       [24]])]


In [50]:
e = np.vsplit(a, 2)
pprint(e)
f = np.vsplit(a, 4)
pprint(f)
g = np.vsplit(a, [1,3])
pprint(g)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]


In [64]:
a = np.random.randint(0, 10, (2, 3))
b = np.random.randint(0, 10, (2, 3))
pprint(a)
pprint(b)

array([[5, 4, 1],
       [5, 8, 9]])
array([[1, 3, 3],
       [7, 9, 2]])


In [65]:
# a배열 파일에 저장
np.save("./my_array1", a)
# a, b 두 개 배열을 파일에 저장
np.savez("my_array2", a, b)

In [66]:
# 1개 배열 로딩
c = np.load("./my_array1.npy")
pprint(c)
# 복수 파일 로딩
npzfiles = np.load("./my_array2.npz")
print(npzfiles.files)
e = npzfiles['arr_0']
f = npzfiles['arr_1']
pprint(e)
pprint(f)

array([[5, 4, 1],
       [5, 8, 9]])
['arr_0', 'arr_1']
array([[5, 4, 1],
       [5, 8, 9]])
array([[1, 3, 3],
       [7, 9, 2]])
